#!/bin/bash

#extract without the apriori GAC values
fout=C20_JIGOGRL02.txt
rm -f $fout

#loop over solution files
for f in ~/work/data/invert/JIGOG/gps_grace_obp/SPP_speciss_delta070910/obpdiagerrAw_grccal_gps10_tudv4_1???
do
BIN_swiss -p=s,v1,r $f | SH_dump -i -m2 -l2 -e | awk '/META/{t=$4}/2    0/{print t,$3,$5}' >> $fout
done